---
gitignore: true

config:
  MD013:
    code_blocks: false
    tables: false
    headings: false
  MD033:
    allowed_elements:
      - br
      - details
      - summary
  MD041: false
  MD024:
    siblings_only: true